[workspace]
resolver = "2"
default-members = ["crates/editor-runner"]

members = [
    "crates/wce_formats", 
    "crates/wce_map", 
    "crates/slkparser",
    "crates/editor-runner"
]

[workspace.dependencies]
pretty_assertions = "^1.4"
derivative = "2.2.0"
derive_more = { version = "2.0.1", features = ["full"]}
log = "0.4.27"
bencher = "0.1.5"
paste = "1.0"
thiserror = "2.0.12"