[package]
name = "war_editor"
version = "0.1.0"
authors = ["Barogthor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slkparser = { path = "slkparser"}
rand = "0.7.0"
bencher = "0.1.5"
byteorder = "1.3.2"
regex = "1.2.1"
lazy_static = "1.3.0"
#getset = "0.0.7"
#jpeg-decoder = "0.1.15"
smart-default = "0.5.2"
mpq = "0.6.0"
image = "0.22.1"
#vec_map = "0.8.1"
rust-ini = "0.13.0"
#num-derive = "0.2.5"
#num = "0.2.0"

