[package]
name = "wce_formats"
version = "0.1.0"
authors = ["Barogthor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
pretty_assertions = {workspace = true}

[dependencies]
derivative = {workspace = true}
byteorder = "1.5.0"
log ={ workspace = true}
# jpeg-decoder = { git = "https://github.com/Barogthor/jpeg-decoder.git" }
image = { version = "0.25.6", features = ["jpeg"]}
rgb = "0.8.52"
mpq = "0.7.0"
bencher = {workspace = true}
thiserror = {workspace = true}