//===========================================================================
// 
// Sandbox Roc
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Sat Aug 02 18:39:22 2025
//   Map Author: Inconnu
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // User-defined
    boolean                 udg_TRUE                   = false

    // Generated
    rect                    gg_rct_Red                 = null
    rect                    gg_rct_LightGreen          = null
    rect                    gg_rct_White               = null
    camerasetup             gg_cam_Camera_001          = null
    sound                   gg_snd_RainAmbience        = null
    sound                   gg_snd_WindLoopStereo      = null
    sound                   gg_snd_RainAmbience01      = null
    sound                   gg_snd_Avatar              = null
    string                  gg_snd_Credits
    trigger                 gg_trg_TriggerEvent        = null
    trigger                 gg_trg_TriggerCondition    = null
    trigger                 gg_trg_TriggerAction       = null
    trigger                 gg_trg_TriggerActionDisabled = null
    trigger                 gg_trg_TriggerDisabledButOn = null
    trigger                 gg_trg_TriggerDisabledNotOn = null
    trigger                 gg_trg_TriggerIfThenElse   = null

    // Random Groups
    integer array gg_rg_000
    integer array gg_rg_001
endglobals

function InitGlobals takes nothing returns nothing
    set udg_TRUE = true
endfunction

//***************************************************************************
//*
//*  Random Groups
//*
//***************************************************************************

function InitRandomGroups takes nothing returns nothing
    local integer curset

    // Group 0 - TestRandGroupUnit
    call RandomDistReset(  )
    call RandomDistAddItem( 0, 95 )
    call RandomDistAddItem( 1, 5 )
    set curset = RandomDistChoose(  )

    if (curset == 0) then
        set gg_rg_000[0] = ChooseRandomCreep( 6 )
        set gg_rg_000[1] = ChooseRandomCreep( 10 )
    elseif (curset == 1) then
        set gg_rg_000[0] = 'nrwm'
        set gg_rg_000[1] = -1
    else
        set gg_rg_000[0] = -1
        set gg_rg_000[1] = -1
    endif

    // Group 1 - TestRandGroupItem
    call RandomDistReset(  )
    call RandomDistAddItem( 0, 50 )
    call RandomDistAddItem( 1, 50 )
    set curset = RandomDistChoose(  )

    if (curset == 0) then
        set gg_rg_001[0] = ChooseRandomItemEx( ITEM_TYPE_CHARGED, 2 )
        set gg_rg_001[1] = 'desc'
    elseif (curset == 1) then
        set gg_rg_001[0] = 'ofro'
        set gg_rg_001[1] = 'desc'
    else
        set gg_rg_001[0] = -1
        set gg_rg_001[1] = -1
    endif

endfunction

//***************************************************************************
//*
//*  Unit Item Tables
//*
//***************************************************************************

function Unit000002_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( ChooseRandomItemEx( ITEM_TYPE_POWERUP, 1 ), 100 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000003_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( 'gopr', 100 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000005_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( ChooseRandomItemEx( ITEM_TYPE_CHARGED, 1 ), 100 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Unit000009_DropItems takes nothing returns nothing
    local widget  trigWidget = null
    local unit    trigUnit   = null
    local integer itemID     = 0
    local boolean canDrop    = true

    set trigWidget = bj_lastDyingWidget
    if (trigWidget == null) then
        set trigUnit = GetTriggerUnit()
    endif

    if (trigUnit != null) then
        set canDrop = not IsUnitHidden(trigUnit)
        if (canDrop and GetChangingUnit() != null) then
            set canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))
        endif
    endif

    if (canDrop) then
        // Item set 0
        call RandomDistReset(  )
        call RandomDistAddItem( gg_rg_001[1], 100 )
        set itemID = RandomDistChoose(  )
        if (trigUnit != null) then
            call UnitDropItem( trigUnit, itemID )
        else
            call WidgetDropItem( trigWidget, itemID )
        endif

    endif

    set bj_lastDyingWidget = null
    call DestroyTrigger(GetTriggeringTrigger())
endfunction


//***************************************************************************
//*
//*  Sounds
//*
//***************************************************************************

function InitSounds takes nothing returns nothing
    set gg_snd_RainAmbience = CreateSound( "Sound\\Ambient\\RainAmbience.wav", false, false, false, 10, 10, "DefaultEAXON" )
    call SetSoundParamsFromLabel( gg_snd_RainAmbience, "AmbientSoundRain" )
    call SetSoundDuration( gg_snd_RainAmbience, 4418 )
    set gg_snd_WindLoopStereo = CreateSound( "Sound\\Ambient\\WindLoopStereo.wav", false, false, false, 10, 10, "DefaultEAXON" )
    call SetSoundParamsFromLabel( gg_snd_WindLoopStereo, "AmbientSoundTestWind" )
    call SetSoundDuration( gg_snd_WindLoopStereo, 11036 )
    set gg_snd_RainAmbience01 = CreateSound( "Sound\\Ambient\\RainAmbience.wav", false, false, false, 10, 10, "DefaultEAXON" )
    call SetSoundParamsFromLabel( gg_snd_RainAmbience01, "AmbientSoundRain" )
    call SetSoundDuration( gg_snd_RainAmbience01, 4418 )
    call SetSoundVolume( gg_snd_RainAmbience01, 127 )
    set gg_snd_Avatar = CreateSound( "Abilities\\Spells\\Human\\Avatar\\Avatar.wav", false, true, true, 10, 10, "SpellsEAX" )
    call SetSoundParamsFromLabel( gg_snd_Avatar, "Avatar" )
    call SetSoundDuration( gg_snd_Avatar, 3199 )
    call SetSoundDistances( gg_snd_Avatar, 650.0, 10010.0 )
    call SetSoundDistanceCutoff( gg_snd_Avatar, 3010.0 )
    set gg_snd_Credits = "Sound\\Music\\mp3Music\\Credits.mp3"
endfunction

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'hmpr', -352.5, 870.1, 43.720 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000002_DropItems )
    set u = CreateUnit( p, 'Hpal', 168.1, 1133.4, 276.280 )
    call SetHeroLevel( u, 3, false )
    call SelectHeroSkill( u, 'AHad' )
    call SelectHeroSkill( u, 'AHad' )
    call UnitAddItemToSlotById( u, 'desc', 0 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000003_DropItems )
    set u = CreateUnit( p, 'hsor', -264.8, 1087.2, 304.970 )
    call IssueImmediateOrder( u, "slowon" )
    set u = CreateUnit( p, 'hrif', 295.1, 703.5, 339.820 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000009_DropItems )
endfunction

//===========================================================================
function CreateNeutralHostile takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'nfsp', 1418.1, -1256.6, 328.510 )
    set life = GetUnitState( u, UNIT_STATE_LIFE )
    call SetUnitState( u, UNIT_STATE_LIFE, 0.95 * life )
    call SetUnitState( u, UNIT_STATE_MANA, 195 )
    set t = CreateTrigger(  )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_DEATH )
    call TriggerRegisterUnitEvent( t, u, EVENT_UNIT_CHANGE_OWNER )
    call TriggerAddAction( t, function Unit000005_DropItems )
    set u = CreateUnit( p, 'nspb', 1245.1, -1403.9, 123.280 )
    call SetUnitAcquireRange( u, 200.0 )
    set unitID = gg_rg_000[0]
    if (unitID != -1) then
        set u = CreateUnit( p, unitID, 1458.8, -1488.8, 187.990 )
    endif
    call RandomDistReset(  )
    call RandomDistAddItem( 'nthl', 34 )
    call RandomDistAddItem( 'nfre', 33 )
    call RandomDistAddItem( 'nsbm', 33 )
    set unitID = RandomDistChoose(  )
    if (unitID != -1) then
        set u = CreateUnit( p, unitID, 1125.5, -1130.6, 308.880 )
    endif
    set unitID = ChooseRandomCreep( 6 )
    if (unitID != -1) then
        set u = CreateUnit( p, unitID, 1024.7, -1549.8, 39.950 )
    endif
endfunction

//===========================================================================
function CreateNeutralPassive takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'nder', 826.4, -595.8, 198.342 )
    set u = CreateUnit( p, 'nder', -1535.6, 1528.1, 278.600 )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings(  )
    call CreateNeutralHostile(  )
    call CreateNeutralPassive(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************

function CreateRegions takes nothing returns nothing
    local weathereffect we

    set gg_rct_Red = Rect( -832.0, -640.0, -480.0, -256.0 )
    set we = AddWeatherEffect( gg_rct_Red, 'RAhr' )
    call EnableWeatherEffect( we, true )
    call SetSoundPosition( gg_snd_RainAmbience, -656.0, -448.0, 0.0 )
    call RegisterStackedSound( gg_snd_RainAmbience, true, 352.0, 384.0 )
    set gg_rct_LightGreen = Rect( 416.0, -32.0, 768.0, 352.0 )
    call SetSoundPosition( gg_snd_Avatar, 592.0, 160.0, 0.0 )
    call RegisterStackedSound( gg_snd_Avatar, true, 352.0, 384.0 )
    set gg_rct_White = Rect( 384.0, -1056.0, 416.0, -640.0 )
endfunction

//***************************************************************************
//*
//*  Cameras
//*
//***************************************************************************

function CreateCameras takes nothing returns nothing

    set gg_cam_Camera_001 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ZOFFSET, 13.5, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ROTATION, 90.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ANGLE_OF_ATTACK, 304.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_TARGET_DISTANCE, 1996.5, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_ROLL, 2.4, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_001, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_Camera_001, 758.2, 178.1, 0.0 )

endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: TriggerEvent
//
// Trigger Event
//===========================================================================
function Trig_TriggerEvent_Actions takes nothing returns nothing
endfunction

//===========================================================================
function InitTrig_TriggerEvent takes nothing returns nothing
    set gg_trg_TriggerEvent = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_TriggerEvent, 5.00 )
    call TriggerAddAction( gg_trg_TriggerEvent, function Trig_TriggerEvent_Actions )
endfunction

//===========================================================================
// Trigger: TriggerCondition
//
// Trigger Condition
//===========================================================================
function Trig_TriggerCondition_Conditions takes nothing returns boolean
    if ( not ( GetIssuedOrderIdBJ() == String2OrderIdBJ("stop") ) ) then
        return false
    endif
    return true
endfunction

function Trig_TriggerCondition_Actions takes nothing returns nothing
endfunction

//===========================================================================
function InitTrig_TriggerCondition takes nothing returns nothing
    set gg_trg_TriggerCondition = CreateTrigger(  )
    call TriggerAddCondition( gg_trg_TriggerCondition, Condition( function Trig_TriggerCondition_Conditions ) )
    call TriggerAddAction( gg_trg_TriggerCondition, function Trig_TriggerCondition_Actions )
endfunction

//===========================================================================
// Trigger: TriggerAction
//
// Trigger Action
//===========================================================================
function Trig_TriggerAction_Actions takes nothing returns nothing
    call TriggerSleepAction( 2 )
endfunction

//===========================================================================
function InitTrig_TriggerAction takes nothing returns nothing
    set gg_trg_TriggerAction = CreateTrigger(  )
    call TriggerAddAction( gg_trg_TriggerAction, function Trig_TriggerAction_Actions )
endfunction

//===========================================================================
// Trigger: TriggerActionDisabled
//
// Trigger Action Disabled
//===========================================================================
function Trig_TriggerActionDisabled_Actions takes nothing returns nothing
endfunction

//===========================================================================
function InitTrig_TriggerActionDisabled takes nothing returns nothing
    set gg_trg_TriggerActionDisabled = CreateTrigger(  )
    call TriggerAddAction( gg_trg_TriggerActionDisabled, function Trig_TriggerActionDisabled_Actions )
endfunction

//===========================================================================
// Trigger: TriggerIfThenElse
//===========================================================================
function Trig_TriggerIfThenElse_Func001001 takes nothing returns boolean
    return ( IsUnitType(GetTriggerUnit(), UNIT_TYPE_STRUCTURE) == true )
endfunction

function Trig_TriggerIfThenElse_Actions takes nothing returns nothing
    if ( Trig_TriggerIfThenElse_Func001001() ) then
        call DoNothing(  )
    else
        call DoNothing(  )
    endif
endfunction

//===========================================================================
function InitTrig_TriggerIfThenElse takes nothing returns nothing
    set gg_trg_TriggerIfThenElse = CreateTrigger(  )
    call TriggerAddAction( gg_trg_TriggerIfThenElse, function Trig_TriggerIfThenElse_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_TriggerEvent(  )
    call InitTrig_TriggerCondition(  )
    call InitTrig_TriggerAction(  )
    call InitTrig_TriggerActionDisabled(  )
    call InitTrig_TriggerIfThenElse(  )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), true )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(1), true )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_007
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerTeam( Player(1), 0 )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 0, 1 )
    call SetStartLocPrio( 0, 0, 1, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 1, 1 )
    call SetStartLocPrio( 1, 0, 0, MAP_LOC_PRIO_HIGH )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -1664.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -1664.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 1664.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 1664.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -1664.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 1664.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 1664.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -1664.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "LordaeronSummerDay" )
    call SetAmbientNightSound( "LordaeronSummerNight" )
    call SetMapMusic( "Music", true, 0 )
    call InitSounds(  )
    call CreateRegions(  )
    call CreateCameras(  )
    call InitRandomGroups(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_001" )
    call SetMapDescription( "TRIGSTR_003" )
    call SetPlayers( 2 )
    call SetTeams( 2 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )

    call DefineStartLocation( 0, 0.0, 256.0 )
    call DefineStartLocation( 1, -1280.0, -1280.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call SetPlayerSlotAvailable( Player(0), MAP_CONTROL_USER )
    call SetPlayerSlotAvailable( Player(1), MAP_CONTROL_USER )
    call InitGenericPlayerSlots(  )
    call InitAllyPriorities(  )
endfunction

