[package]
name = "slkparser"
version = "0.1.0"
authors = ["Barogthor <f.thery3103@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "slk_bench"
harness = false