[package]
name = "wce_map"
version = "0.1.0"
authors = ["Barogthor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
pretty_assertions = { workspace = true }

[dependencies]
slkparser = { path = "../slkparser" }
wce_formats = { path = "../wce_formats" }
regex = "1.3.6"
smart-default = "0.6.0"
lazy_static = "1.3.0"

bencher = {workspace = true}
log = { workspace = true}
derivative = { workspace = true}
paste = {workspace = true}